movq 0x5e(%rip), %rax
cmp %rax, %rbx
nopl %eax, (%rax)
cmp $0x33, %ebx
movq 0x28(%rip), %r8
movq 0x19a(%rip), %rcx
cmp %r8, %rcx
nopl %eax, (%rax)
lea 0x14(%rip), %r10
mov $-0x7777, %rcx
jmpq *0x777f(%rsp,%rcx,1)
add $0x8, %rsp
lea 0x2(%rip), %rdx
call *%rdx
add $0x6, %r9
add %r9, %r10
sub $0x8, %r8
sub %r8, %r10
imul %r10
imul %r11, %r10
imul $0x77, %r11, %r10
and %rax, %rbx
or $0x13, %rbx
or %rcx, %rbx
not %rcx
neg %rcx
shl $0x7, %rdi
sar $0x3, %rdi
mov $0x4519, %rax
pxor %xmm0, %xmm0
cvtsi2ss %rax, %xmm0
sqrtss %xmm0, %xmm1
comiss %xmm0, %xmm1
cvttss2si %xmm1, %rax
movq -0x100(%rsp), %rax
test %rax, %rax
xor %esi, %esi
movq -0x100(%rsp,%rsi,8), %rax
test %rax, %rax
movq -0x100(%rsp,%rsi,8), %rax
movq %gs:-0x100(%rsp,%rsi,8), %rcx
cmp %rax, %rcx
movl 0xa000000, %ecx
inc %esi
movq 0xa000000(%rax,%rsi,8), %rcx
movq 0xa000000(,%rsi,8), %rdx
cmp %rcx, %rdx
movq 0xa000008, %rdx
cmp %rcx, %rdx
xor %eax, %eax
inc %eax
mov %eax, %edi
inc %rdi
lea 0x54(%rip), %rsi
mov $0x7, %rdx
PASSED
xor %edi, %edi
