movq 0x5e(%rip), %rax
mov $0x8877665544332211, %rbx
cmp %rax, %rbx
movq 0x19a(%rip), %rcx
mov $-0x7777, %rcx
add $0x8, %rsp
lea 0x2(%rip), %rdx
and $0xfe, %rax
and %rax, %rbx
or $0x13, %rbx
or %rcx, %rbx
not %rcx
neg %rcx
shl $0x7, %rdi
sar $0x3, %rdi
mov $0x4519, %rax
cvtsi2ss %rax, %xmm0
cvttss2si %xmm1, %rax
cmp $0x85, %rax
movq -0x100(%rsp), %rax
test %rax, %rax
movq -0x100(%rsp,%rsi,8), %rax
test %rax, %rax
movq -0x100(%rsp,%rsi,8), %rax
movq %gs:-0x100(%rsp,%rsi,8), %rcx
cmp %rax, %rcx
movq 0xa000000(%rax,%rsi,8), %rcx
movq 0xa000000(,%rsi,8), %rdx
cmp %rcx, %rdx
movq 0xa000008, %rdx
cmp %rcx, %rdx
inc %rdi
lea 0x54(%rip), %rsi
mov $0x7, %rdx
PASSED
